parameters:
- name: environmentTagName
  type: string
- name: dependencies
  type: object
- name: environmentName
  type: string
- name: environmentId
  type: string
- name: sharedEnvironmentId
  type: string
- name: serviceConnection
  type: string
- name: variableTemplates
  type: object

stages:
- stage: Deploy_${{parameters.environmentId}}
  dependsOn: 
    - '${{ each dependency in parameters.dependencies }}':
      - '${{dependency}}'
  variables:
    - group: platform-global-marcom
    - group: platform-${{parameters.environmentName}}
    - group: platform-${{parameters.environmentName}}-marcom
    - name: BaseName
      value: "s126${{parameters.environmentId}}-mcom-${{parameters.environmentName}}"
    - name: ResourceGroupName
      value: '$(BaseName)'
    - name: EnvironmentName
      value: ${{ parameters.environmentName }}
    - name: environmentTagName
      value: ${{parameters.environmentTagName}}
    - '${{ each variableTemplate in parameters.variableTemplates }}':
      - template: '${{variableTemplate}}'      
      
  displayName: '${{parameters.environmentName}} [${{parameters.environmentId}}] deployment'
  jobs:  
  - template: ../jobs/marketingcommunications-infrastructure-job.yml
    parameters:
      BaseName: $(BaseName)
      serviceConnection: ${{ parameters.serviceConnection }}
      sharedEnvironmentId: ${{ parameters.sharedEnvironmentId }}
      environmentName: ${{parameters.environmentName}}

  - template: ../jobs/marketingcommunications-generate-configs-job.yml
    parameters:
      serviceConnection: ${{ parameters.serviceConnection }}
      sharedEnvironmentId: ${{ parameters.sharedEnvironmentId }}

  - template: ../jobs/marketingcommunications-publish-site-job.yml
    parameters:
      serviceConnection: ${{ parameters.serviceConnection }}
      sharedEnvironmentId: ${{ parameters.sharedEnvironmentId }}
  
  - template: ../jobs/marketingcommunications-publish-function-job.yml
    parameters:
      serviceConnection: ${{ parameters.serviceConnection }}
      sharedEnvironmentId: ${{ parameters.sharedEnvironmentId }}

  - template: ../jobs/marketingcommunications-post-deployment-job.yml
