parameters:
- name: environmentTagName
  type: string
- name: dependencies
  type: object
- name: environmentName
  type: string
- name: sharedEnvironmentId
  type: string
- name: serviceConnection
  type: string

stages:
- stage: DeploySharedInfrastructure_${{parameters.sharedEnvironmentId}}
  dependsOn: 
    - '${{ each dependency in parameters.dependencies }}':
      - '${{dependency}}'
  variables:
    - group: platform-global-matching
    - group: platform-${{parameters.environmentName}}
    - group: platform-${{parameters.environmentName}}-matching
    - name: SharedBaseName
      value: "s126${{parameters.sharedEnvironmentId}}-matching"
    - name: SharedResourceGroup
      value: '$(SharedBaseName)-shared'
    - name: SharedSQLServerName
      value: '$(SharedBaseName)-shared-sqlsvr'
    - name: environmentTagName
      value: ${{parameters.environmentTagName}}
      
  displayName: '${{parameters.environmentName}} [${{parameters.sharedEnvironmentId}}] Shared' 
  jobs:
  - template: ../jobs/matching-shared-infrastructure-job.yml
    parameters:
      baseName: $(SharedBaseName)
      serviceConnection: ${{ parameters.serviceConnection }}
      sharedEnvironmentId: ${{ parameters.sharedEnvironmentId }}
      environmentName: ${{parameters.environmentName}}