# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  WebAppName: 'tl-marketing-and-communication'
  Sku: 'F1'
  Location: 'northeurope'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: build
        arguments: '--configuration $(BuildConfiguration)'
        projects: '**/*.csproj'
      
    - task: DotNetCoreCLI@2
      inputs:
        command: publish
        publishWebProjects: True
        arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
        zipAfterPublish: True
      
    - task: CopyFiles@2
      inputs:
        Conents: azuredeploy.json
        OverWrite: true
        TargetFolder: '$(build.artifactstagingdirectory)'
      
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
- stage: 'Deploy ARM'
  jobs:
  - deployment: DeployArm
    displayName: 'Deploy to Test Env'
    environment: 'tl-marketing-NLB-Test'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureResourceGroupDeployment@2
            inputs:
              azureSubscription: 'Nlb-Test'
              resourceGroupName: 'NLB-Learning'
              location: 'UK West'
              templateLocation: 'Linked artifact'
              csmFile: '$(System.DefaultWorkingDirectory)/_nbowes24.tl-marketing-and-communication/drop/azuredeploy.json'
              overrideParameters: '-webAppName "$(WebAppName)" -sku "$(Sku)" -location "$(Location)"'
