# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  batch: true
  branches:
    include:
      - "*"

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  WebAppName: 'tl-marketing-and-communication'
  Sku: 'F1'
  Location: 'northeurope'
  ArtifactName: 'drop'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: gittools.gitversion.gitversion-task.GitVersion@5
      displayName: GitVersion
      inputs:
        updateAssemblyInfo: true

    - task: DotNetCoreCLI@2
      inputs:
        command: build
        arguments: '--configuration $(BuildConfiguration)'
        projects: '**/*.csproj'
      
    - task: DotNetCoreCLI@2
      inputs:
        command: publish
        publishWebProjects: True
        arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
        zipAfterPublish: True
      
    - task: CopyFiles@2
      inputs:
        Conents: azuredeploy.json
        OverWrite: true
        TargetFolder: '$(build.artifactstagingdirectory)'
      
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
            
