resources:
  repositories:
    - repository: self
      persistCredentials: true
      clean: true

    - repository: devopsTemplates
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/operations-devops-pipeline-templates
      ref: feature/TLD-376-remove-output-secrets

    - repository: devopsTools
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/operations-devops-tools

trigger:
  branches:
    include: 
    - master 
    - develop  
    - feature/*
     
pr: 
  - feature/* 
  - master
  - develop

pool:
  name: 'Azure Pipelines'
  vmImage: 'windows-latest'
  
variables:
  applicationName: marketingcommunications
stages:
  - template: ./yaml/stages/marketingcommunications-master-stage.yml
