# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  WebAppName: 'tl-marketing-and-communication'
  Sku: 'F1'
  Location: 'northeurope'
  ArtifactName: 'drop'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: build
        arguments: '--configuration $(BuildConfiguration)'
        projects: '**/*.csproj'
      
    - task: DotNetCoreCLI@2
      inputs:
        command: publish
        publishWebProjects: True
        arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
        zipAfterPublish: True
      
    - task: CopyFiles@2
      inputs:
        Conents: azuredeploy.json
        OverWrite: true
        TargetFolder: '$(build.artifactstagingdirectory)'
      
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'

- stage: Deploy
  jobs:
  - deployment: Deploy
    displayName: 'Deploy to Dev Env'
    environment: 'tl-marketing-NLB-Test'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              artifactName: $(ArtifactName)
              buildType: 'current'
              downloadType: 'single'
              downloadPath: '$(System.ArtifactsDirectory)'
          - task: AzureResourceGroupDeployment@2
            inputs:
              azureSubscription: 'Nlb-Test'
              resourceGroupName: 'NLB-Learning'
              location: 'UK West'
              templateLocation: 'Linked artifact'
              csmFile: '$(System.ArtifactsDirectory)/drop/azuredeploy.json'
              overrideParameters: '-webAppName "$(WebAppName)" -sku "$(Sku)" -location "$(Location)"'
          - task: AzureRMWebAppDeployment@4
            inputs:
              connectionType: 'AzureRM'
              connectedServiceName: 'Nlb-Test'
              webAppName: 'tl-marketing-and-communication-NLB-webapp'
              webAppKind: 'Web App On Windows'
              package: '$(build.artifactstagingdirectory)'
            