parameters:
  - name: serviceConnection
    type: string
  - name: sharedEnvironmentId
    type: string
  - name: tableName
    type: string
    default: 'configuration'
jobs:
- job: GenerateConfigs
  variables:
    ConfigStorageAccountName: $[ stageDependencies.DeploySharedInfrastructure_${{parameters.sharedEnvironmentId}}.DeploySharedInfrastructure_${{parameters.sharedEnvironmentId}}.outputs['DeploySharedInfrastructure_${{parameters.sharedEnvironmentId}}.armOutputs.armOutput.ConfigStorageAccountName'] ]
    SqlConnectionString: $[ dependencies.DeploySQLDatabase.outputs['SqlVariables.SqlConnectionString'] ]
    BlobStorageConnectionString : $[ dependencies.DeployMarketingCommunicationsInfrastructure.outputs['armOutputs.armOutput.StorageConnectionString'] ]
    TableStorageConnectionString : $[ dependencies.DeployMarketingCommunicationsInfrastructure.outputs['armOutputs.armOutput.StorageConnectionString'] ]

  pool:
    name: 'Azure Pipelines'
    vmImage: 'windows-latest'
  dependsOn:
    - DeployMarketingCommunicationsInfrastructure
  steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(System.ArtifactsDirectory)'

    - task: GenerateEnvironmentConfiguration@3
      displayName: 'Process schemas in $(System.ArtifactsDirectory)/drop/config'
      inputs:
        SourcePath: '$(System.ArtifactsDirectory)/drop/config'
        ServiceConnectionName: ${{ parameters.serviceConnection}}
        StorageAccountName: '$(ConfigStorageAccountName)'
        TableName: Configuration
