jobs:
  - job: PostDeployment
    pool:
        name: 'Azure Pipelines'
        vmImage: 'windows-2019'
    dependsOn: 
    - PublishSite
    - PublishFunction
    steps:
      - task: GitHubRelease@1
        displayName: 'GitHub release (create)'
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master') , eq(variables['System.JobAttempt'], '1'))
        inputs:
          gitHubConnection: SkillsFundingAgency
          tagSource: userSpecifiedTag
          tag: '$(Build.BuildNumber)'