parameters:
  - name: serviceConnection
    type: string
  - name: sharedEnvironmentId
    type: string
jobs:
- job: PublishFunction
  variables:
    WorkerFunctionAppName: $[ dependencies.DeployMarketingCommunicationsInfrastructure.outputs['armOutputs.armOutput.WorkerFunctionAppName'] ]

  pool:
    name: 'Azure Pipelines'
    vmImage: 'windows-latest'
  dependsOn:
    - DeployMarketingCommunicationsInfrastructure
    - GenerateConfigs
  steps:
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'current'
      downloadType: 'single'
      artifactName: 'drop'
      downloadPath: '$(System.ArtifactsDirectory)'

  - task: AzureFunctionApp@1
    inputs:
      azureSubscription: ${{ parameters.serviceConnection }}
      appType: 'functionApp'
      appName: '$(WorkerFunctionAppName)'
      package: '$(System.ArtifactsDirectory)/appdrop/Sfa.Tl.Marketing.Communications.Functions.zip'
      deploymentMethod: 'auto'
