parameters:
  - name: baseName
    type: string
  - name: serviceConnection
    type: string
  - name: sharedEnvironmentId
    type: string
  - name: environmentName
    type: string
  - name: globalSignServiceAccountPassword
    type: string
jobs:

  - deployment: DeploySharedInfrastructure_${{parameters.sharedEnvironmentId}}
    displayName: Deploy Shared Infrastructure
    environment: "${{parameters.environmentName}}"
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
            - checkout: devopsTools
            - template: ./Infrastructure/steps/deploy-template.yml@devopsTemplates
              parameters:
                serviceConnection: ${{ parameters.serviceConnection }}
                subscriptionId: $(subscriptionId)
                resourceGroupName: $(SharedResourceGroup)
                location: 'West Europe'
                templateFilePath: './tl-marketing-and-communication/azure/marketingcommunications-shared.json'
                armParameterOverrideString: '-environmentNameAbbreviation "${{parameters.baseName}}" 
                  -appServicePlanTier "$(AppServicePlanTier)"
                  -appServicePlanSize "$(AppServicePlanSize)"
                  -appServicePlanInstances "$(AppServicePlanInstances)"
                  -azureWebsitesRPObjectId "$(AzureWebsitesRPObjectId)"
                  -keyVaultReadWriteObjectIds "$(KeyVaultReadWriteObjectIds)"
                  -keyVaultFullAccessObjectIds "$(keyVaultFullAccessObjectIds)"'
                tags: $(Tags)                
                processOutputs: true
            - pwsh: Write-Host "##vso[task.setvariable variable=SharedResourceGroup;isOutput=true]$(SharedResourceGroup)"
              name: SharedVariables

#            - task: AzureCLI@2
#              displayName: 'Migrate Key Vault to RBAC'
#              inputs:
#                azureSubscription: ${{ parameters.serviceConnection }}
#                scriptType: bash
#                scriptLocation: inlineScript
#                inlineScript: |
#                  az keyvault update \
#                    --name "$(armOutputs.armoutput.sharedKeyVaultName)" \
#                    --resource-group "$(SharedResourceGroup)" \
#                    --enable-rbac-authorization true

            - task: AzurePowerShell@5
              displayName: 'Create Configuration Table'
              inputs:
                azureSubscription: ${{ parameters.serviceConnection }}
                ScriptType: InlineScript
                Inline: |
                  $account = Get-AzStorageAccount -ResourceGroupName $(SharedResourceGroup) -Name $(armOutputs.armoutput.configStorageAccountName)
                  $table = Get-AzStorageTable -Context $account.Context -Name Configuration -ErrorAction SilentlyContinue
                  if (!$table) {
                      New-AzStorageTable -Context $account.Context -Name Configuration
                  }
                azurePowerShellVersion: LatestVersion
                pwsh: true

            - task: AzurePowerShell@5
              displayName: 'Set Certificate Issuer and Contacts'
              inputs:
                azureSubscription: ${{ parameters.serviceConnection }}
                ScriptType: 'FilePath'
                ScriptPath: './operations-devops-tools/Powershell/SetKeyVaultConfig/SetKeyVaultConfig.ps1'
                ScriptArguments: '-SharedKeyVaultName "$(armOutputs.armoutput.sharedKeyVaultName)" -GlobalSignServiceAccountId $(GlobalSignServiceAccountId) -KvContactEmailAddress $(KvContactEmailAddress) -CaAdminFirstName $(CaAdminFirstName) -CaAdminLastName $(CaAdminLastName) -CaAdminEmailAddress $(CaAdminEmailAddress)'
                FailOnStandardError: true
                azurePowerShellVersion: LatestVersion
              env: 
                globalSignServiceAccountPassword: $(GlobalSignServiceAccountPassword)