parameters:
  - name: serviceConnection
    type: string
  - name: sharedEnvironmentId
    type: string
jobs:
- job: PublishSite
  variables:
    ConfigStorageAccountName: $[ stageDependencies.DeploySharedInfrastructure_${{parameters.sharedEnvironmentId}}.DeploySharedInfrastructure_${{parameters.sharedEnvironmentId}}.outputs['DeploySharedInfrastructure_${{parameters.sharedEnvironmentId}}.armOutputs.armOutput.ConfigStorageAccountName'] ]
    uiAppName: $[ dependencies.DeployMatchingInfrastructure.outputs['armOutputs.armOutput.uiAppName'] ]

  pool:
    name: 'Azure Pipelines'
    vmImage: 'windows-2019'
  dependsOn: 
    - DeployMatchingInfrastructure
    - GenerateConfigs
  steps:
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'current'
      downloadType: 'single'
      artifactName: 'appdrop'
      downloadPath: '$(System.ArtifactsDirectory)'

  # - task: AzureWebApp@1
  #   inputs:
  #     azureSubscription: ${{ parameters.serviceConnection }}
  #     appType: 'webApp'
  #     appName: '$(uiAppName)'
  #     deployToSlotOrASE: true
  #     resourceGroupName: '$(ResourceGroupName)'
  #     slotName: 'staging'
  #     package: '$(System.ArtifactsDirectory)/appdrop/Sfa.Tl.Matching.Web.zip'
  #     deploymentMethod: 'auto'
  
  - task: AzureRmWebAppDeployment@3
    displayName: 'Azure App Service Deploy: $(uiAppName)'
    inputs:
      azureSubscription: ${{ parameters.serviceConnection }}
      WebAppName: '$(uiAppName)'
      DeployToSlotFlag: true
      ResourceGroupName: '$(ResourceGroupName)'
      SlotName: 'staging'
      Package: '$(System.ArtifactsDirectory)/appdrop/Sfa.Tl.Matching.Web.zip'
      UseWebDeploy: true
      RemoveAdditionalFilesFlag: true

  - task: AzureAppServiceManage@0
    inputs:
      azureSubscription: ${{ parameters.serviceConnection }}
      Action: 'Start Azure App Service'
      WebAppName: '$(uiAppName)'
      SpecifySlotOrASE: true
      ResourceGroupName: '$(ResourceGroupName)'
      Slot: 'staging'
  

  - task: AzureAppServiceManage@0
    displayName: 'Swap Slots: $(uiAppName)'
    inputs:
      azureSubscription: ${{ parameters.serviceConnection }}
      WebAppName: '$(uiAppName)'
      ResourceGroupName: '$(ResourceGroupName)'
      SourceSlot: staging
  
  - task: AzureAppServiceManage@0
    displayName: 'Delete swap Slot: $(uiAppName)'
    inputs:
      azureSubscription: ${{ parameters.serviceConnection }}
      Action: 'Delete Slot'
      WebAppName: '$(uiAppName)'
      ResourceGroupName: '$(ResourceGroupName)'
      Slot: 'staging'